spring.application.name=worthsnap-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/worthsnap
spring.datasource.username=worthsnap
spring.datasource.password=worthsnap

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
